modLoader="javafml" #mandatory
loaderVersion="[38,)"
license="CC0"
issueTrackerURL="https://github.com/CorgiTaco/MultiLoader-Template/issues" #optional
[[mods]]
modId="modid"
version="${file.jarVersion}"
displayName="Example Mod"
displayURL="https://github.com/CorgiTaco/MultiLoader-Template/"
logoFile="multiloader.png"
credits=""
authors="Corgi Taco"
description='''
'''
[[dependencies.modid]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[38,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.modid]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
