modLoader="javafml" #mandatory
loaderVersion="[43,)"
license="CC0"
issueTrackerURL="https://github.com/CorgiTaco/MultiLoader-Template/issues" #optional
[[mods]]
modId="usefulutilities"
version="${file.jarVersion}"
displayName="Useful Utilities"
displayURL="https://github.com/YaBoiChips/Useful-Utilities/"
logoFile="multiloader.png"
credits=""
authors="YaBoiChips, AOCAWOL, DorkUp55"
description='''
'''
[[dependencies.usefulutilities]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.usefulutilities]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
